name: Deploy GitHub repository to cPanel
#Contributor Insta @SuperiorStar, also thanks to SamKirkland
on:
  push:
    branches:
      - live
jobs:
  FTP-Deploy-Action:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        run: |
          echo "DATE_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
          
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: ğŸ“‚ Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

      - name: Send email notification on success
        if: success()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: mail.gluehost.in
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'Success: ${{ env.REPO_NAME }} cPanel Deployment Lift-off! ğŸš€'
          body: |
            Hey there, ğŸ‰
            
            Project: ${{ env.REPO_NAME }}
            Committer: ${{ github.actor }}

            Great news! Your latest code changes have successfully landed on the cPanel runway at ${{ env.DATE_TIME }}. The deployment was as smooth as butter. Give yourself a pat on the back and celebrate this milestone! ğŸ¥³

            If you have any questions or want to share your victory dance, hit reply. Happy coding! ğŸ’»

          to: ${{ secrets.REPO_OWNER_EMAILS }}
          from: Github Actions ğŸš€

      - name: Send email notification on failure
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: mail.gluehost.in
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'ğŸ›‘ Oh No! Deployment Alert!'
          body: |
            Uh-oh! ğŸš¨

            Project: ${{ env.REPO_NAME }}
            Committer: ${{ github.actor }}

            Unfortunately, the deployment to cPanel hit a snag at ${{ env.DATE_TIME }}. Don't panic, though! Take a deep breath and dive into the logs to unravel this mystery. You've got this! ğŸ’ª

            If you need a hand or just want to vent, feel free to reach out. We're all in this together! ğŸ¤

          to: ${{ secrets.REPO_OWNER_EMAILS }}
          from: Github Actions ğŸš€
